<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textSENT</name>
   <tag></tag>
   <elementGuidId>05c0c32b-bdfe-41c4-aa68-02dbfbc180f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[2]//div[1]//p[contains(text(),'SENT')][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[2]//div[1]//p[contains(text(),'SENT')][1]</value>
   </webElementProperties>
</WebElementEntity>
