<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textRECEIVED</name>
   <tag></tag>
   <elementGuidId>b1771336-047c-4439-9af9-dfb7460319af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[2]//div[1]//p/span[contains(text(),'RECEIVED')][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[2]//div[1]//p/span[contains(text(),'RECEIVED')][1]</value>
   </webElementProperties>
</WebElementEntity>
