<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textWarningOwnData</name>
   <tag></tag>
   <elementGuidId>b6ce1eab-e4ef-4248-aa95-ffcf6c563bc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body//p[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body//p[1]</value>
   </webElementProperties>
</WebElementEntity>
