<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header2Content-Security-Policy</name>
   <tag></tag>
   <elementGuidId>af256a18-6829-42f2-a394-4b813ca24a4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='collapseHeaderRules']//div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='collapseHeaderRules']//div[2]</value>
   </webElementProperties>
</WebElementEntity>
