<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>header1dave.masters.dev1.bi.nuText</name>
   <tag></tag>
   <elementGuidId>a79221dd-e7d8-469e-bd57-dc8010492e23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(text(),'dev1.bi.nu')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(text(),'dev1.bi.nu')]</value>
   </webElementProperties>
</WebElementEntity>
